spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

app:
  jwt:
    secret: ${APP_JWT_SECRET}
  upload-dir: /app/uploads

logging:
  level:
    com.bugxyz: INFO
